---
type: "RectangularWorld"
size:  # in meters
  - 15
  - 15
seed: 2023
spawners:
  - type: UniformAgentSpawner
    n: 10  # default number of agents BUT may be overridden by user args
    facing: away
    region: [[6.9, 6.9], [6.9, 8.1], [8.1, 8.1], [8.1, 6.9]]
    agent: !include flockbot.yaml
metadata:
  hash: _hash
# stop_at: 2000 # Upper Simulation Limit (timesteps)
