[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "novel_swarms"
version = "1.0.0a"
requires-python = ">=3.11"
authors = [
  { name="Connor Mattson", email="c.mattson@utah.edu" },
  { name="Kevin Zhu", email="kzhu4@gmu.edu" },
]
maintainers = [{ name="Kevin Zhu", email="kzhu4@gmu.edu" }]
description = "An agent-based swarm simulator"
readme = {file = "README.md", content-type = "text/markdown"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "cma",
    "matplotlib",
    "numpy",
    "opencv-python",
    "ripser",
    "pillow",
    "pygame-ce",
    "PyYAML>=6.0.1",
    "scipy",
    "scikit-learn",
    "thorpy",
    "circle_fit",
    "shapely",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "isort",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
]
shapes = ["pointpats"]
docs = [
    "pydata-sphinx-theme~=0.16.1",
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-togglebutton",
    "sphinx-design",
    "numpydoc",
    "myst-parser",
    "tqdm",
]

[project.urls]
"Homepage" = "https://github.com/kenblu24/RobotSwarmSimulator"
"Bug Tracker" = "https://github.com/kenblu24/RobotSwarmSimulator/issues"