---
type: "Goalbot"
sensors:
  custom_state_decision: "Linear"
  sensors:
    - type: "BinaryFOVSensor"
      theta: 0.2   # Vision Angle / 2 (Radians) (previously 0.3141595)
      degrees: false
      agent_sensing_range: 17 # In Body Lengths
      show: true
      goal_sensing_range: 17
      use_goal_state: false
      wall_sensing_range: 17
      fn: 0.10
      fp: 0.05
      bias: 0 # Angle Bias for Sensor
      store_history: false
      seed: 10
controller: "self"
agent_radius: 0.5
stop_at_goal: false
dt: 0.13
body_color:
  - 255
  - 0
  - 0
body_filled: true